// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByDwtnC5yBxIwD0WsGSLMW4Ohwws0ZM-s',
    appId: '1:806951747650:web:1b6b23b2f2f1ee55f9eddb',
    messagingSenderId: '806951747650',
    projectId: 'union-shop-f1ed2',
    authDomain: 'union-shop-f1ed2.firebaseapp.com',
    storageBucket: 'union-shop-f1ed2.firebasestorage.app',
    measurementId: 'G-CCSRMXETYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXqEIP0W8ZyxodM_SIHwXhbJBlx5Nbcs',
    appId: '1:806951747650:android:300955dbd94c124cf9eddb',
    messagingSenderId: '806951747650',
    projectId: 'union-shop-f1ed2',
    storageBucket: 'union-shop-f1ed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTFkwOjsuZcNLlywKB4FMhhOg_Hlqbe3M',
    appId: '1:806951747650:ios:a623879caa9af37df9eddb',
    messagingSenderId: '806951747650',
    projectId: 'union-shop-f1ed2',
    storageBucket: 'union-shop-f1ed2.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTFkwOjsuZcNLlywKB4FMhhOg_Hlqbe3M',
    appId: '1:806951747650:ios:a623879caa9af37df9eddb',
    messagingSenderId: '806951747650',
    projectId: 'union-shop-f1ed2',
    storageBucket: 'union-shop-f1ed2.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByDwtnC5yBxIwD0WsGSLMW4Ohwws0ZM-s',
    appId: '1:806951747650:web:4b4988a747b3aa1cf9eddb',
    messagingSenderId: '806951747650',
    projectId: 'union-shop-f1ed2',
    authDomain: 'union-shop-f1ed2.firebaseapp.com',
    storageBucket: 'union-shop-f1ed2.firebasestorage.app',
    measurementId: 'G-NWJT27ZG8H',
  );
}
